# Generated by Django 3.2.9 on 2021-11-27 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='name',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='file',
            old_name='path',
            new_name='url',
        ),
    ]
